---
- hosts: all  
  gather_facts: false
  become: false
  vars: 
    dir_path: "{{ morpheus['customOptions']['dirpath'] }}"
    file_to_touch: "{{ morpheus['customOptions']['filetotouch'] }}"
    full_path:  "{{ morpheus['customOptions']['dirpath'] }}\\{{ morpheus['customOptions']['filetotouch'] }}"
  tasks:
    - name: Debug Output
      debug:
        msg: "{{ full_path }}"

    - name: Create directory structure
      ansible.windows.win_file:
        path: "{{ dir_path }}"
        state: directory

    - name: Touch a file 
      ansible.windows.win_file:
        path: "{{ full_path }}"
        state: touch

    - name: Run an executable using win_command
      ansible.windows.win_command: whoami.exe
      