---
- hosts: all  
  gather_facts: false
  become: false
  vars: 
    file_to_touch: "{{ morpheus['customOptions']['filetotouch'] }}"
  tasks:
    - name: Touch a file 
      ansible.windows.win_file:
        path: "{{file_to_touch}}"
        state: touch
        