---
- hosts: all  
  vars: 
    file_to_touch: "{{ morpheus['customOptions']['filetotouch'] }}"
  tasks:
    - name: create a file if it doesnt exist
      become: true
      file:
        path: "{{file_to_touch}}"
        state: touch
        mode: '0644'
    - name: ls
      command: ls /tmp